// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import Example1Controller from "./example1_controller"
application.register("example1", Example1Controller)

import Example2Controller from "./example2_controller"
application.register("example2", Example2Controller)

import Example3Controller from "./example3_controller"
application.register("example3", Example3Controller)

import Example4Controller from "./example4_controller"
application.register("example4", Example4Controller)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
